export const GET_BOOKING_LIST = 'GET_BOOKING_LIST';
export const BOOKING_SEAT = 'BOOKING_SEAT';
export const BOOKING_TICKET = 'BOOKING TICKET';
export const UPDATE_BOOKING_FROM_OTHER_CLIENT = 'UPDATE_BOOKING_FROM_OTHER_CLIENT';