export const GET_BANNER_LIST = 'GET BANNER LIST';
export const GET_FILM_LIST = 'GET FILM LIST';
export const GET_FILM_PLAYING_LIST = 'GET FILM PLAYING LIST';
export const GET_FILM_UPCOMING_LIST = 'GET FILM UPCOMING LIST';
export const GET_FILM_BY_ID = 'GET_FILM_BY_ID';
