export const GET_INFORMATION_OF_THEATERS = 'GET INFORMATION OF THEATERS';
export const GET_INFORMATION_OF_THEATERS_BY_SYSTEM = 'GET INFORMATION OF THEATERS BY SYSTEM';
export const GET_INFORMATION_OF_RELEASE_FILM = 'GET INFORMATION OF RELEASE FILM';
export const GET_INFORMATION_OF_THEATER_BY_FILM = 'GET INFORMATION OF THEATER BY FILM';