export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const THONG_TIN_TAI_KHOAN = 'THONG_TIN_TAI_KHOAN';
export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG';
export const LAY_DANH_SACH_LOAI_NGUOI_DUNG = 'LAY_DANH_SACH_LOAI_NGUOI_DUNG';
export const LAY_DANH_SACH_NGUOI_DUNG_THEO_TAI_KHOAN = 'LAY_DANH_SACH_NGUOI_DUNG_THEO_TAI_KHOAN';